apiVersion: v1
kind: Service
metadata:
  name: my-simprest-svc
  labels:
    app: simprest
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: simprest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simprest
  labels:
    app: simprest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simprest
  template:
    metadata:
      labels:
        app: simprest
    spec:
      containers:
      - name: simprest
        image: qishan789/simprest:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
