name: Docker Image CI - B

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: show package
      run: pwd && ls -l
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: change dir
      run: cd src && ls -l
    - name: show dir
      run: pwd && ls -l && echo "look like each RUN is put to the default dir!"
