name: Docker Image CI - B

on:
  workflow_dispatch:
  
env:
  APP_NAME: ${{ github.event.repository.name }} # 06_simpRest
  THIS_WORKFLOW_NAME: ${{ github.workflow }} # Docker Image CI - B
  WORKING_DIR: ${{ github.workspace }}
  EVENT_NAME: ${{ github.event_name }}
  BRANCH_NAME: ${{ github.ref_name }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: show package
      run: pwd && ls -l
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: change dir
      run: cd src && ls -l
    - name: show dir
      run: |
        pwd && ls -l && echo "look like each RUN is put to the default dir!"
        git version
        mvn -version
      
  deploy2:
  
    runs-on: ubuntu-latest
    steps:
    - name:  show env
      run: |-
        pwd && ls -l
        echo "APP_NAME=$APP_NAME"
        echo "THIS_WORKFLOW_NAME=$THIS_WORKFLOW_NAME"
        echo " WORKING_DIR=$WORKING_DIR "
        echo " EVENT_NAME=$EVENT_NAME "
        echo " BRANCH_NAME=$BRANCH_NAME "
